name: pypi_package_dev
channels:
  - defaults
dependencies:
  - jupyterlab=1.2.6
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.0.1
  - pip=20.0.2
  - pytest=5.3.5
  - python=3.8.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - pip:
      - pytest-cov==2.10.0
      - setuptools>=51.1.2
      - twine>=3.3.0
      - wheel>0.36.2
